language: php
sudo: false
dist: trusty

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.1

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install: travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist

script: vendor/bin/phpunit -c tests/phpunit.xml

jobs:
  include:
    - stage: Test (dev dependencies)

    - stage: Test (stable dependencies)
      install:
        - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist --prefer-stable

    - stage: Test (lowest stable dependencies)
      install:
        - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist --prefer-lowest --prefer-stable

    - stage: Lint
      script:
        - vendor/bin/parallel-lint -e php,phpt --exclude vendor .
        - vendor/bin/phpstan.phar analyse --ansi --no-progress -l7 -c phpstan.neon src tests
        - vendor/bin/phpcs --standard=ruleset.xml --encoding=utf-8 -sp src tests

    - stage: Coverage
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
        - travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      install:
        - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist --prefer-stable
      script:
        - vendor/bin/phpunit --coverage-clover tests/coverage.xml -c tests/phpunit.xml
        - php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml
